version: '3'
services:
  db-postgres:
    image: postgres
    env_file: ./postgres/.env_sample
    ports:
      - "5432:5432"
    networks:
      app_net:
        ipv4_address: 172.20.3.3
    depends_on:
      - django

  django:
    build: ./django
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - ./:/code
    networks:
      app_net:
        ipv4_address: 172.20.3.2
    tty: true

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.3.0/24
volumes:
  est-data: